version: '3.1'

services:
  db:
    image: mongo:4.4
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=msgs_db
    volumes:
      - .:/docker-entrypoint-initdb.d
